---
name: Catalyst-Plugin-Flavour
version: 0.029_01
author:
  - 'Daisuke Murase E<lt>typester@cpan.orgE<gt>'
abstract: Catalyst plugin for request flavours.
license: perl
requires:
  Catalyst: 5.50
provides:
  Catalyst::Plugin::Flavour:
    file: lib/Catalyst/Plugin/Flavour.pm
    version: 0.029_01
  Catalyst::Plugin::Flavour::Data:
    file: lib/Catalyst/Plugin/Flavour/Data.pm
  Catalyst::Request:
    file: lib/Catalyst/Plugin/Flavour.pm
    version: 0.029_01
generated_by: Module::Build version 0.2612
