---
name: Catalyst-Plugin-Flavour
version: 0.02
author:
  - 'Daisuke Murase E<lt>typester@cpan.orgE<gt>'
abstract: Catalyst plugin for request flavours.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.50
provides:
  Catalyst::Plugin::Flavour:
    file: lib/Catalyst/Plugin/Flavour.pm
    version: 0.02
generated_by: Module::Build version 0.2703
